---
title: Disorderly Dev Duck
email: catod@ulrik.uio.no
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: ''
twitter_username: jekyllrb
github_username: petrickow
test: fesk
markdown: kramdown
timezone: Europe/Paris
