---
title: Disorderly Dev Duck
email: catod@ulrik.uio.no
description: |
  Experimenting with jekyll and forestry.io to see if it might be a good combination for future projects.
baseurl: ''
url: http://devduck.me
github_username: petrickow
markdown: kramdown
timezone: Europe/Paris
